### ISSUE TITLE
Serialized types emit too much data

### ISSUE THREAD

**Issue by Thraka** [thesadrogue/TheSadRogue.Primitives#27]
The primitive types should skip properties that just represent aspects of the type but not the real data. For example, serializing the `Rectangle` results in more information than needed. Obviously, only the `x,y,width,height` is needed.

```json
  "View": {
    "$type": "SadRogue.Primitives.Rectangle, TheSadRogue.Primitives",
    "Height": 10,
    "Width": 10,
    "X": 0,
    "Y": 0,
    "Area": 100,
    "Center": {
      "$type": "SadRogue.Primitives.Point, TheSadRogue.Primitives",
      "X": 5,
      "Y": 5
    },
    "IsEmpty": false,
    "MaxExtent": {
      "$type": "SadRogue.Primitives.Point, TheSadRogue.Primitives",
      "X": 9,
      "Y": 9
    },
    "MaxExtentX": 9,
    "MaxExtentY": 9,
    "MinExtent": {
      "$type": "SadRogue.Primitives.Point, TheSadRogue.Primitives",
      "X": 0,
      "Y": 0
    },
    "MinExtentX": 0,
    "MinExtentY": 0,
    "Position": {
      "$type": "SadRogue.Primitives.Point, TheSadRogue.Primitives",
      "X": 0,
      "Y": 0
    },
    "Size": {
      "$type": "SadRogue.Primitives.Point, TheSadRogue.Primitives",
      "X": 10,
      "Y": 10
    }
  }
```

**Comment by Chris3606** [comment]
Most of those shouldn't be being serialized in the current configuration. Most of the fields shown in that output are read-only properties. I was under the impression those cannot be serialized, and if I remember correctly I cannot mark them with the nonserializable tag as such, so I have no idea why they're in any serialization output.  I'll run some tests and see what I can come up with.

**Comment by Thraka** [comment]
Well I think it also depends on what serializer is being used. How come you can't mark it as nonserializable ?

**Comment by Chris3606** [comment]
I think it might be possible to force-tag a property as non-serializable by using `[field:NonSerielized]`, it may assist with that behavior.

However, while the way newtonsoft parses, I think it uses its own ignore attributes so I'm not sure it will make a difference.  And worse, this isn't an issue entirely specific to newtonsoft -- `XMLSerializer`, a built-in C# type, also ignores `NonSerialized` attributes, and instead requires you to use XML-specific ones as far as I can tell.

There seems to be an incredible amount of inconsistency with C# serialization APIs.  The `XMLSerializer` not only serializes everything not marked with xml-specific ignore attributes regardless of `NonSerializable` tags, but passing our primitives through an `XMLSerializer` is completely non-functional currently, for 2 reasons:
- `XMLSerializer` (unlike other serializers) requires the type to have a public, parameter-less constructor
- Even assuming all the types had one such constructor, the deserialization via `XML` would also fail because it would try to assign to read-only properties.

I think we may need to re-open this, at least to run some tests and consider how we can generally better support serialization.

**Comment by Thraka** [comment]
The `XmlSerializer` will ignore anything with `XmlIgnore` attribute too, but that may be specific to just that serializer. My experience with newtonsoft is it will respect the attributes created by the other serializers, both `XmlSerializer` and `DataContractSerializer`

I'm not sure if I would use `XmlSerializer` over `DataContractSerializer` for anything.

**Comment by Chris3606** [comment]
I can't see a reason to offhand.  However, [this documentation](https://www.newtonsoft.com/json/help/html/PropertyJsonIgnore.htm) for newtonsoft's json serialization seems to imply it has its own tags for ignoring properties.  Even if it also respects `DataContractSerializer` tags, if the `[field:NonSerialized]` attribute still isn't allowed to be placed on properties, then it doesn't appear that there is a way to properly specify the serializable fields via attributes, which means you end up having to write serializer-specific translation classes in those cases, which to be honest feels ridiculously complicated for simply serializing a type -- I was hoping there's a more generically applicable way to do it.

**Comment by Chris3606** [comment]
I can't test right now, but [this article](https://stackoverflow.com/questions/2022035/why-do-i-need-field-in-my-attribute-declaration-fieldnonserialized) seems to imply that `[field:NonSerialized]` will work to mark the backing field of an auto-generated property as non-serializable, which I believe is what we need.  Assuming the Newtonsoft JSON serializer properly respects `DataContractSerializer` tags, this should prevent the behavior that you're seeing?
