### ISSUE TITLE
GetHashCode of Area is not consistent with Equals

### ISSUE THREAD

**Issue by Chris3606** [thesadrogue/TheSadRogue.Primitives#44]
Currently, GetHashCode in area returns the position set's hash code.  There are a number of problems with this:
- The position's hash code is based on the address of the hash set, not the values in the hash set
- The equality operator is based on `Positions`, not the positions _set_; so even if the hash code was appropriate, these two would not match.

The broader issue appears to be that mutable types (reference or value) should not be overloading `Equals` or `operator==`, according to [Microsoft guidelines](https://docs.microsoft.com/en-us/dotnet/api/system.object.equals?view=netcore-3.1) (see Guidelines for Reference Types section).  This begs the question of what the intended method is to have such equality methods, as the same stipulations seem to apply to [IEquatable<T>](https://docs.microsoft.com/en-us/dotnet/api/system.iequatable-1?view=netcore-3.1).

This may warrant more research, but I believe the Microsoft-intended method for providing these types of operations seems to be to provide a custom function, for area perhaps `HasSamePoints`.  I feel like this makes rather sloppy code personally, but there seems to be no other approach that follows guidelines as far as I'm seeing currently.  Suggestions are welcome.

**Comment by SadConsole** [comment]
This scenario is good to understand. SadConsole probably violates these rules to some degree. The suggestions in these rules make sense though. I think when comparing two reference types for value equality, where the values are mutable, it makes sense to have some sort of explicit `Matches` or `HasSamePoints` method where you're checking the values instead of the reference.

I need to really evaluate how I'm doing this in the `Cell` type because I'm sure I've done something wrong here.

**Comment by Chris3606** [comment]
I know GoRogue is violating this rules too; in fact there is a linked issue in GoRogue above about this.  I agree that, despite the minor inconvenience, I think it's best to have such types have some explicit method for comparison (`Matches` or the like).  This follows Microsoft guidelines, which despite the inconvenience I do feel are well-founded.  It also stays consistent with the notion that if I call `.Equals` or `x == y`, I don't expect the operation to take a long time; certainly not time proportional to the number of items the object contains.

To meet these guidelines as far as the primitives library is concerned, we'd need to change `Area`, `BoundedRectangle`, `Gradient`, and `Palette`.  Regarding naming, we have a couple options I can see:
1. Choose a generic name we use for all the types in the primitives library, such as `IsEquivalentTo` or `Matches`.
2. Choose a name that attempts to specifically imply how the comparison is performed, such as `HasSamePoints` in the case of `Area`.

Personally, I favor option 1 because it creates a more consistent feel across types, and doesn't leave the door open to imprecise naming as often.  For example, `HasSamePoints` may actually _not_ be a good name for the `Area` function, because the current implementation of comparison compares the _order_ of points as well, and that isn't implied in the name.  A generic name such as `IsEquivalentTo` or `Matches` (or similar generic names, for that matter) would avoid such ambiguity and imply that you need to read the method description to know what the comparison does.

It would also be possible to implement this function in an interface, however I'm not sure this is necessary/beneficial.

**Comment by Thraka** [comment]
I read some more guidelines and it's stated that `GetHashCode` should never change for the object. It should be constant throughout the lifetime of the object, otherwise you run the risk of losing the object if it's added to a hashset/table, which makes sense. It doesn't give an alternative though when you do want this comparison.

Regarding the names, I feel like `IsEquivalentTo` is too verbose while `Matches` is succinct.

Regarding the testing of order though, would you expect users using `Matches` to invoke this to care about ordering or just be more concerned that they point to the same set of points?

**Comment by Chris3606** [comment]
> GetHashCode should never change for the object

Yep, which is why avoiding defining it (and thus avoiding defining `Equals`) for mutable types is a good idea.

Regarding the order, truthfully I don't see the need to compare areas for equivalency coming up very often at all.  The reason the current implementation takes into account order is `Area` is pitched to the user as an augmented `List`, which is ordered.  But truthfully ordering probably wouldn't ever matter and could be removed from the implementation.

In any case, I'll get this changed to `Matches` in this (and any other mutable types).
